version: "3.8"
services:
  react:
    build: ./docker/react
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/var/www/html/frontend
    working_dir: /var/www/html/frontend
    command: sh -c "npm install && npm run build && npm start"